### BUILD STEP: react packages
FROM node:bookworm AS webpack
# Copy webpack config
COPY package.json ./
COPY package-lock.json ./
# Install dependencies
RUN npm install

# Copy files
COPY webpack.config.js webpack.config.js
COPY .babelrc .babelrc
COPY tsconfig.json tsconfig.json
RUN mkdir -p ytdownloader/static/js
COPY ytdownloader/react_src/ /ytdownloader/react_src

# Build
RUN PROD_BUILD=true npm run build

### BUILD STEP: python packages
FROM python:3.12-slim-bookworm AS python
RUN apt-get -y update && apt-get install -y curl && curl -sSL https://install.python-poetry.org | python3 -
COPY ytdownloader/poetry.lock ytdownloader/pyproject.toml ./
RUN /root/.local/bin/poetry export --without-hashes --format=requirements.txt --with web > requirements.txt

### FINAL STEP
FROM python:3.12-slim-bookworm
# Copy over requirements.txt
COPY --from=python /requirements.txt .
RUN python3 -m pip install --user --no-cache-dir -r requirements.txt

# Copy application
WORKDIR /opt/ytdownloader

COPY ytdownloader/static ./static
COPY ytdownloader/templates ./templates
COPY ytdownloader/main.py ytdownloader/tasks.py ./ 
# Copy React build files
COPY --from=webpack /ytdownloader/static/js/ /opt/ytdownloader/static/js/

# Start
CMD exec /root/.local/bin/gunicorn --bind 0.0.0.0:80 --reload main:app
