services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
      args:
        PROD_BUILD: "true"
    restart: unless-stopped
    depends_on:
      - redis
      - celery
    ports:
      - "5000:80"
    volumes:
      - download:/opt/ytdownloader/tmp
    env_file:
      - .env
  celery:
    build:
      context: ./
      dockerfile: Dockerfile.celery
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - download:/opt/ytdownloader/tmp
  redis:
    image: redis
    restart: unless-stopped
volumes:
  download: {}
