services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
      args:
        PROD_BUILD: "false"
    restart: unless-stopped
    depends_on:
      - redis
      - celery
    ports:
      - "5000:80"
    volumes:
      - download:/opt/ytdownloader/tmp
      - ./ytdownloader/static/dist:/opt/ytdownloader/ytdownloader/static/dist:ro
      - ./ytdownloader/templates:/opt/ytdownloader/ytdownloader/templates:ro
      - ./ytdownloader/main.py:/opt/ytdownloader/ytdownloader/main.py:ro
  celery:
    build:
      context: ./
      dockerfile: Dockerfile.celery
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - download:/opt/ytdownloader/tmp
  redis:
    image: redis
    restart: unless-stopped
volumes:
  download: {}
